apiVersion: apps/v1
kind: Deployment
metadata:
  name: writing-deployment
  labels:
    app: writing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writing
  template:
    metadata:
      labels:
        app: writing
    spec:
      containers:
      - name: writing
        image: quay.io/ernesgonzalez33/writing:latest
        resources:
          limits:
            ephemeral-storage: "1Mi"
          requests:
            ephemeral-storage: "1Mi"