apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limit-resources"
spec:
  limits:
    - type: "Container"
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "1Mi"
      default:
        cpu: "500m"
        memory: "500Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"